### ISSUE TITLE
libpam-python must be installed

### ISSUE THREAD

**Issue by martin3000** [philippmeisberger/pam-face#1]
libpam-python must be installed for the installation to work.

**Comment by philippmeisberger** [comment]
That's correct. The Debian package has a dependency on it:
https://github.com/philippmeisberger/pam-face/blob/41b6958781fb96058701be6ff822634daf358858/debian/control#L19

**Comment by martin3000** [comment]
In ubuntu I got an error about this. Maybe you can mention it as a prerequisite in the readme.

**Comment by philippmeisberger** [comment]
Can you provide the error message?

**Comment by martin3000** [comment]
`sudo dpkg -i ../libpam-face*.deb`

Selecting previously unselected package libpam-face.
(Reading database ... 384192 files and directories currently installed.)
Preparing to unpack ../libpam-face_1.0_all.deb ...
Unpacking libpam-face (1.0) ...
dpkg: dependency problems prevent configuration of libpam-face:
 libpam-face depends on libpam-python; however:
  Package libpam-python is not installed.

dpkg: error processing package libpam-face (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 libpam-face

**Comment by philippmeisberger** [comment]
Please see https://github.com/philippmeisberger/pam-face/blob/master/README.md#installation-of-the-latest-version: Install missing dependencies by running `sudo apt-get install -f`

**Comment by martin3000** [comment]
It looks like python module ConfigParser is required, but not standard.

**Comment by philippmeisberger** [comment]
`ConfigParser` is listed under standard library: https://docs.python.org/2/library/configparser.html
