### ISSUE TITLE
'module' object has no attribute 'createLBPHFaceRecognizer'

### ISSUE THREAD

**Issue by martin3000** [philippmeisberger/pam-face#2]
Running pamface-conf I get "'module' object has no attribute 'createLBPHFaceRecognizer'".
This is because openCV changed the names.
The old name is createLBPHFaceRecognizer().
The new name is LBPHFaceRecognizer_create().

**Comment by philippmeisberger** [comment]
Which version of OpenCV are you using? Yesterday I tried `cv2.face.createLBPHFaceRecognizer` on OpenCV 3.2 which worked.

I also found this: https://github.com/opencv/opencv/issues/7187

**Comment by martin3000** [comment]
The change came with version 3.3

**Comment by sachinAcchi** [comment]
The new name is LBPHFaceRecognizer_create()
but i am getting error that is object has no attribute 'LBPHFaceRecognizer_create'

**Comment by philippmeisberger** [comment]
Which version are you using?

**Comment by phiweGuan** [comment]
4.1.1

**Comment by ghost** [comment]
This worked for me 
model = cv2.face.LBPHFaceRecognizer_create()
 since I am using Python 3
