### ISSUE TITLE
pamface-conf --check-user jms

### ISSUE THREAD

**Issue by martin3000** [philippmeisberger/pam-face#4]
Running pamface-conf --check-user user1 I get:

'cv2.face_LBPHFaceRecognizer' object has no attribute 'load'

The "load" function as been renamed to "read".

**Comment by philippmeisberger** [comment]
Oh I see: https://stackoverflow.com/questions/46873728/cv2-lbphfacerecognizer-has-no-attribute-load-predict

**Comment by philippmeisberger** [comment]
It seems I need a wrapper around OpenCV to support versions 2 and 3

**Comment by martin3000** [comment]
You have already a wrapper in `__init__.py`
