### ISSUE TITLE
cv2.imshow() does not work in wayland with sudo

### ISSUE THREAD

**Issue by martin3000** [philippmeisberger/pam-face#7]
Running a program with sudo and using cv2.imshow() does not work in wayland.
Error:
`X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x270

X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 3 (X_ShmPutImage)
  Resource id:  0x440000d
`

**Comment by martin3000** [comment]
This can be easily solved. In pamface-conf, function addUser:
try:
=>        import pwd
            os.seteuid(pwd.getpwnam(os.getlogin()).pw_uid) 
            ## camera can be index or path
            camera = self.__config.get('Global', 'Camera')
            ....

            faceRecognizer.update(images, numpy.array(labels))
=>        os.seteuid(0)
            faceRecognizer.save(MODELS_FILE)

**Comment by philippmeisberger** [comment]
The fix will cause this error with GTK+:

(process:12178): Gtk-WARNING **: This process is currently running setuid or setgid.
This is not a supported use of GTK+. You must create a helper
program instead. For further details, see:

    http://www.gtk.org/setuid.html

Refusing to initialize GTK+.

**Comment by martin3000** [comment]
The error comes from seteuid(user) or from seteuid(0) ?

**Comment by philippmeisberger** [comment]
Error is caused by `seteuid(user)`

**Comment by martin3000** [comment]
Hahaha, very smart from GTK to prevent uid change from 0 to 1001 !
Could be a security breach :-)

**Comment by philippmeisberger** [comment]
Added workaround for this: Introduced `--no-gui` switch in `pamface-conf`
